name: Maven Build

on:
  push:
    branches:
      - main  # This means the workflow will run whenever there’s a push to the 'main' branch
  pull_request:
    branches:
      - main  # This means the workflow will also run on pull requests to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The workflow will run on a Linux environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out your code from the GitHub repository

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Set the Java version to 17, required for Maven to work

    - name: Build with Maven
      run: |
        mvn clean install   # Runs the 'clean' and 'install' goals
        mvn compile         # Runs the 'compile' goal
        mvn test            # Runs the 'test' goal
        mvn package         # Runs the 'package' goal
        mvn install         # Runs the 'install' goal
        mvn deploy          # Runs the 'deploy' goal
        mvn validate        # Runs the 'validate' goal
        mvn verify          # Runs the 'verify' goal
        mvn site            # Runs the 'site' goal
